package org.nescent.plhdb.hibernate.dao;

import java.util.Date;

/**
 * Biography generated by hbm2java
 */
@SuppressWarnings("unchecked")
public class Biography implements java.io.Serializable {

	private int animOid;
	private String animname;
	private String birthgroup;
	private Character bgqual;
	private Character sex;
	private String momid;
	private Character firstborn;
	private Date birthdate;
	private Date entrydate;
	private String entrytype;
	private Date departdate;
	private Double departdateerror;
	private String departtype;
	private String studyid;
	private String animid;
	private Date bdmin;
	private Date bdmax;
	private String bddist;

	public Biography() {
	}

	public Biography(int animOid) {
		this.animOid = animOid;
	}

	public Date getBdmin() {
		return bdmin;
	}

	public void setBdmin(Date bdmin) {
		this.bdmin = bdmin;
	}

	public Date getBdmax() {
		return bdmax;
	}

	public void setBdmax(Date bdmax) {
		this.bdmax = bdmax;
	}

	public String getBddist() {
		return bddist;
	}

	public void setBddist(String bddist) {
		this.bddist = bddist;
	}

	public int getAnimOid() {
		return animOid;
	}

	public void setAnimOid(int animOid) {
		this.animOid = animOid;
	}

	public String getStudyid() {
		return studyid;
	}

	public void setStudyid(String studyid) {
		this.studyid = studyid;
	}

	public String getAnimid() {
		return this.animid;
	}

	public void setAnimid(String animid) {
		this.animid = animid;
	}

	public String getAnimname() {
		return this.animname;
	}

	public void setAnimname(String animname) {
		this.animname = animname;
	}

	public String getBirthgroup() {
		return this.birthgroup;
	}

	public void setBirthgroup(String birthgroup) {
		this.birthgroup = birthgroup;
	}

	public Character getBgqual() {
		return this.bgqual;
	}

	public void setBgqual(Character bgqual) {
		this.bgqual = bgqual;
	}

	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	public String getMomid() {
		return this.momid;
	}

	public void setMomid(String momid) {
		this.momid = momid;
	}

	public Character getFirstborn() {
		return this.firstborn;
	}

	public void setFirstborn(Character firstborn) {
		this.firstborn = firstborn;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public Date getEntrydate() {
		return this.entrydate;
	}

	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}

	public String getEntrytype() {
		return this.entrytype;
	}

	public void setEntrytype(String entrytype) {
		this.entrytype = entrytype;
	}

	public Date getDepartdate() {
		return this.departdate;
	}

	public void setDepartdate(Date departdate) {
		this.departdate = departdate;
	}

	public Double getDepartdateerror() {
		return this.departdateerror;
	}

	public void setDepartdateerror(Double departdateerror) {
		this.departdateerror = departdateerror;
	}

	public String getDeparttype() {
		return this.departtype;
	}

	public void setDeparttype(String departtype) {
		this.departtype = departtype;
	}

}
