package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * CvtermRelationship generated by hbm2java
 */
public class CvtermRelationship implements java.io.Serializable {

	private int cvtermRelationshipOid;
	private Cvterm cvtermByPredicateOid;
	private Cvterm cvtermByObjectOid;
	private Cvterm cvtermBySubjectOid;

	public CvtermRelationship() {
	}

	public CvtermRelationship(int cvtermRelationshipOid,
			Cvterm cvtermByPredicateOid, Cvterm cvtermByObjectOid,
			Cvterm cvtermBySubjectOid) {
		this.cvtermRelationshipOid = cvtermRelationshipOid;
		this.cvtermByPredicateOid = cvtermByPredicateOid;
		this.cvtermByObjectOid = cvtermByObjectOid;
		this.cvtermBySubjectOid = cvtermBySubjectOid;
	}

	public int getCvtermRelationshipOid() {
		return this.cvtermRelationshipOid;
	}

	public void setCvtermRelationshipOid(int cvtermRelationshipOid) {
		this.cvtermRelationshipOid = cvtermRelationshipOid;
	}

	public Cvterm getCvtermByPredicateOid() {
		return this.cvtermByPredicateOid;
	}

	public void setCvtermByPredicateOid(Cvterm cvtermByPredicateOid) {
		this.cvtermByPredicateOid = cvtermByPredicateOid;
	}

	public Cvterm getCvtermByObjectOid() {
		return this.cvtermByObjectOid;
	}

	public void setCvtermByObjectOid(Cvterm cvtermByObjectOid) {
		this.cvtermByObjectOid = cvtermByObjectOid;
	}

	public Cvterm getCvtermBySubjectOid() {
		return this.cvtermBySubjectOid;
	}

	public void setCvtermBySubjectOid(Cvterm cvtermBySubjectOid) {
		this.cvtermBySubjectOid = cvtermBySubjectOid;
	}

}
