package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * IndividualRelationship generated by hbm2java
 */
public class IndividualRelationship implements java.io.Serializable {

	private int individualRelationshipOid;
	private Individual individualByChildOid;
	private Individual individualByParentOid;
	private String reltype;

	public IndividualRelationship() {
	}

	public IndividualRelationship(int individualRelationshipOid,
			Individual individualByChildOid, Individual individualByParentOid,
			String reltype) {
		this.individualRelationshipOid = individualRelationshipOid;
		this.individualByChildOid = individualByChildOid;
		this.individualByParentOid = individualByParentOid;
		this.reltype = reltype;
	}

	public int getIndividualRelationshipOid() {
		return this.individualRelationshipOid;
	}

	public void setIndividualRelationshipOid(int individualRelationshipOid) {
		this.individualRelationshipOid = individualRelationshipOid;
	}

	public Individual getIndividualByChildOid() {
		return this.individualByChildOid;
	}

	public void setIndividualByChildOid(Individual individualByChildOid) {
		this.individualByChildOid = individualByChildOid;
	}

	public Individual getIndividualByParentOid() {
		return this.individualByParentOid;
	}

	public void setIndividualByParentOid(Individual individualByParentOid) {
		this.individualByParentOid = individualByParentOid;
	}

	public String getReltype() {
		return this.reltype;
	}

	public void setReltype(String reltype) {
		this.reltype = reltype;
	}

}
