package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * IndividualRelationships generated by hbm2java
 */
public class IndividualRelationships implements java.io.Serializable {

	private IndividualRelationshipsId id;

	public IndividualRelationships() {
	}

	public IndividualRelationships(IndividualRelationshipsId id) {
		this.id = id;
	}

	public IndividualRelationshipsId getId() {
		return this.id;
	}

	public void setId(IndividualRelationshipsId id) {
		this.id = id;
	}

}
