package org.nescent.plhdb.hibernate.dao;

import java.util.Date;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * Observations generated by hbm2java
 */
public class Observations implements java.io.Serializable {

    private ObservationsId id;
    private Date timeOfObservation;
    private Double timeError;
    private String eventType;
    private String eventCode;
    private String eventTypeParent;
    private String eventTypeNamespace;
    private Integer individualOid;

    public Observations() {
    }

    public Observations(ObservationsId id) {
	this.id = id;
    }

    public ObservationsId getId() {
	return this.id;
    }

    public void setId(ObservationsId id) {
	this.id = id;
    }
    public Date getTimeOfObservation() {
	return this.timeOfObservation;
    }

    public void setTimeOfObservation(Date timeOfObservation) {
	this.timeOfObservation = timeOfObservation;
    }

    public Double getTimeError() {
	return this.timeError;
    }

    public void setTimeError(Double timeError) {
	this.timeError = timeError;
    }

    public String getEventType() {
	return this.eventType;
    }

    public void setEventType(String eventType) {
	this.eventType = eventType;
    }

    public String getEventCode() {
	return this.eventCode;
    }

    public void setEventCode(String eventCode) {
	this.eventCode = eventCode;
    }

    public String getEventTypeParent() {
	return this.eventTypeParent;
    }

    public void setEventTypeParent(String eventTypeParent) {
	this.eventTypeParent = eventTypeParent;
    }

    public String getEventTypeNamespace() {
	return this.eventTypeNamespace;
    }

    public void setEventTypeNamespace(String eventTypeNamespace) {
	this.eventTypeNamespace = eventTypeNamespace;
    }

    public Integer getIndividualOid() {
	return this.individualOid;
    }

    public void setIndividualOid(Integer individualOid) {
	this.individualOid = individualOid;
    }
}
