package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * Role generated by hbm2java
 */
public class Permission implements java.io.Serializable {

    private int permissionOid;
    private String access;
    private String study;
    private UserAccount userAccount;

    public Permission() {
    }

    public String getAccess() {
	return access;
    }

    public void setAccess(String access) {
	this.access = access;
    }

    public String getStudy() {
	return study;
    }

    public void setStudy(String study) {
	this.study = study;
    }

    public UserAccount getUserAccount() {
	return userAccount;
    }

    public void setUserAccount(UserAccount userAccount) {
	this.userAccount = userAccount;
    }

    public int getPermissionOid() {
	return permissionOid;
    }

    public void setPermissionOid(int permissionOid) {
	this.permissionOid = permissionOid;
    }

}
