package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * Recordingperiod generated by hbm2java
 */
public class Recordingperiod implements java.io.Serializable {

    private int recordingperiodOid;
    private Observation observationByStartOid;
    private Cvterm cvterm;
    private Observation observationByEndOid;

    public Recordingperiod() {
    }

    public Recordingperiod(int recordingperiodOid,
	    Observation observationByStartOid, Cvterm cvterm) {
	this.recordingperiodOid = recordingperiodOid;
	this.observationByStartOid = observationByStartOid;
	this.cvterm = cvterm;
    }

    public Recordingperiod(int recordingperiodOid,
	    Observation observationByStartOid, Cvterm cvterm,
	    Observation observationByEndOid) {
	this.recordingperiodOid = recordingperiodOid;
	this.observationByStartOid = observationByStartOid;
	this.cvterm = cvterm;
	this.observationByEndOid = observationByEndOid;
    }

    public int getRecordingperiodOid() {
	return this.recordingperiodOid;
    }

    public void setRecordingperiodOid(int recordingperiodOid) {
	this.recordingperiodOid = recordingperiodOid;
    }

    public Observation getObservationByStartOid() {
	return this.observationByStartOid;
    }

    public void setObservationByStartOid(Observation observationByStartOid) {
	this.observationByStartOid = observationByStartOid;
    }

    public Cvterm getCvterm() {
	return this.cvterm;
    }

    public void setCvterm(Cvterm cvterm) {
	this.cvterm = cvterm;
    }

    public Observation getObservationByEndOid() {
	return this.observationByEndOid;
    }

    public void setObservationByEndOid(Observation observationByEndOid) {
	this.observationByEndOid = observationByEndOid;
    }

}
