package org.nescent.plhdb.hibernate.dao;

// Generated Dec 12, 2007 11:49:54 AM by Hibernate Tools 3.2.0.CR1

/**
 * RecordingperiodsId generated by hbm2java
 */
public class RecordingperiodsId implements java.io.Serializable {

	private Integer individualOid;
	private Integer startObservationOid;

	public RecordingperiodsId() {
	}

	public RecordingperiodsId(Integer individualOid, Integer startObservationOid) {
		this.individualOid = individualOid;
		this.startObservationOid = startObservationOid;

	}

	public Integer getIndividualOid() {
		return this.individualOid;
	}

	public void setIndividualOid(Integer individualOid) {
		this.individualOid = individualOid;
	}

	public Integer getStartObservationOid() {
		return this.startObservationOid;
	}

	public void setStartObservationOid(Integer startObservationOid) {
		this.startObservationOid = startObservationOid;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordingperiodsId))
			return false;
		RecordingperiodsId castOther = (RecordingperiodsId) other;

		return ((this.getIndividualOid() == castOther.getIndividualOid()) || (this
				.getIndividualOid() != null
				&& castOther.getIndividualOid() != null && this
				.getIndividualOid().equals(castOther.getIndividualOid())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIndividualOid() == null ? 0 : this.getIndividualOid()
						.hashCode());
		result = 37
				* result
				+ (getStartObservationOid() == null ? 0 : this
						.getStartObservationOid().hashCode());

		return result;
	}

}
